[package]
name = "gpiozero"
version = "0.1.0"
authors = ["Rahul Thakoor <rahul.thakoor@gmail.com>"]
repository = "https://github.com/rahul-thakoor/rust_gpiozero.git"
homepage = "https://github.com/rahul-thakoor/rust_gpiozero.git"
license = "MIT"
readme = "README.md"
documentation = ""
description = "A library inspired by gpiozero in Rust."




[dependencies]
sysfs_gpio = "0.5.1"
#rppal = "0.2.0"


